-- Create Storage Bucket for user images
-- Note: This creates the bucket in the storage schema
-- File size limit: 50MB (Supabase Free Plan limit)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'user-images',
  'user-images',
  true,
  52428800,
  ARRAY['image/png', 'image/jpeg', 'image/webp', 'image/gif']
)
ON CONFLICT (id) DO NOTHING;

-- Enable RLS on storage.objects
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Allow authenticated uploads to user-images" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated to view user-images" ON storage.objects;

-- Create policy to allow authenticated users to upload to user-images bucket
CREATE POLICY "Allow authenticated uploads to user-images"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'user-images'
);

-- Create policy to allow public read access to files in user-images bucket
-- This is necessary for public URLs generated by getPublicUrl() to work
CREATE POLICY "Allow public read access to user-images"
ON storage.objects FOR SELECT
TO PUBLIC
USING (
  bucket_id = 'user-images'
);

-- Create policy to allow authenticated users to update their own files
CREATE POLICY "Allow authenticated to update user-images"
ON storage.objects FOR UPDATE
TO authenticated
USING (
  bucket_id = 'user-images' AND
  auth.uid()::text = (storage.foldername(name))[1]
);

-- Create policy to allow authenticated users to delete their own files
CREATE POLICY "Allow authenticated to delete user-images"
ON storage.objects FOR DELETE
TO authenticated
USING (
  bucket_id = 'user-images' AND
  auth.uid()::text = (storage.foldername(name))[1]
);

-- Grant usage on user-images bucket to authenticated users
GRANT USAGE ON SCHEMA storage TO authenticated;
GRANT ALL ON SCHEMA storage TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA storage TO authenticated;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA storage TO authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA storage TO authenticated;

-- Modify user_images table to store file paths instead of base64
-- Note: We'll keep the columns as TEXT but store file paths/URLs instead of base64 data

-- Add columns if they don't exist
ALTER TABLE user_images ADD COLUMN IF NOT EXISTS original_image_path TEXT;
ALTER TABLE user_images ADD COLUMN IF NOT EXISTS generated_image_path TEXT;

-- Migrate existing data (optional - if you have existing base64 data, you might want to keep it)
-- This is a one-time migration to move from base64 to storage
-- Uncomment the following if you want to migrate existing data:

/*
-- Function to migrate existing base64 images to storage
CREATE OR REPLACE FUNCTION migrate_images_to_storage()
RETURNS VOID AS $$
DECLARE
  image_record RECORD;
  file_name TEXT;
  upload_result RECORD;
BEGIN
  FOR image_record IN SELECT id, user_id, original_image, generated_image, prompt FROM user_images WHERE original_image_path IS NULL LOOP
    -- Upload original image
    file_name := image_record.user_id || '/' || image_record.id || '_original.png';
    
    INSERT INTO storage.objects (name, bucket_id, owner, metadata)
    VALUES (
      file_name,
      'user-images',
      image_record.user_id,
      jsonb_build_object('original_id', image_record.id)
    );
    
    -- Upload generated image
    file_name := image_record.user_id || '/' || image_record.id || '_generated.png';
    
    INSERT INTO storage.objects (name, bucket_id, owner, metadata)
    VALUES (
      file_name,
      'user-images',
      image_record.user_id,
      jsonb_build_object('generated_id', image_record.id)
    );
    
    -- Update user_images with paths
    UPDATE user_images
    SET 
      original_image_path = image_record.user_id || '/' || image_record.id || '_original.png',
      generated_image_path = image_record.user_id || '/' || image_record.id || '_generated.png'
    WHERE id = image_record.id;
  END LOOP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Run migration (uncomment to execute)
-- SELECT migrate_images_to_storage();
*/
